docs/quick-start/platform-installation.md

After changing the KubeRocketCI portal endpoint, it is required to update the guidelines in our documentation (see the screenshot below).

docs: Update the portal endpoint in quick guide (#184)

---

docs/operator-guide/edp-access-model.md

Please include a summary of the change and why it is needed.
Fixes # (issue)
- [+] I have performed a self-review of my own code
- [+] I have made corresponding changes to the documentation
- [+] My changes generate no new warnings
- [+] Pull Request contain one commit. I squash my commits
Add any other context or screenshots about the feature request here.

docs: Update the EDP Access Model page #175

---

deploy-templates/templates/rbac/role_developer.yaml

This Pull Request introduces changes to the role_developer.yaml file within our deploy-templates/templates/rbac/ directory. Specifically, it removes excessive permissions that were previously granted to developers, aligning the rights more closely with the principle of least privilege. The adjustments include the removal of list, create, update, and watch verbs for certain resources, ensuring developers have only the necessary level of access to perform their tasks efficiently.
Fixes # (issue)
The reduced permissions have been tested in a development environment to confirm that developers still have the access necessary to perform their expected tasks without interruption. Testing involved:
Verifying that developers could still execute essential operations on applications and …

chore: Align rights excessive removed(#191)

---

docs/developer-guide/aws-infrastructure-cost-estimation.md
mkdocs.yml

This PR introduces a new page under the Developer Guide section, specifically within Cloud Providers -> AWS, that details the approximate costs of our AWS infrastructure. The page aims to help developers plan and budget for AWS infrastructure costs more effectively by providing an estimated cost for each platform component.
Fixes # (issue)
- The page has been reviewed for accuracy against AWS's current pricing.
- Links to the AWS Pricing Calculator have been tested to ensure they are functional and correctly pre-configured.
This documentation page is a proactive step towards better budget management and planning for our AWS infrastructure. It consolidates scattered information into a single, accessible location.

docs: AWS Infrastructure Cost Estimation Page (#202)

---

deploy-templates/README.md
deploy-templates/templates/external-secrets/externalsecret-kaniko.yaml
deploy-templates/templates/external-secrets/externalsecret-regcred.yaml
deploy-templates/values.yaml

chore: Add eso objects for GHCR registry (#218)

---

deploy-templates/README.md
deploy-templates/templates/external-secrets/externalsecret-keycloak-broker.yaml
deploy-templates/templates/keycloak/broker-idp.yaml
deploy-templates/templates/keycloak/keycloakauthflow.yaml
deploy-templates/templates/keycloak/realm.yaml
deploy-templates/values.yaml

Please include a summary of the change and why it is needed.

feat: Migrate from SSORealm to idp resources

---

deploy-templates/templates/external-secrets/externalsecret-keycloak-broker.yaml

fix: Update keycloak secret definition

---

deploy-templates/templates/keycloak/broker-idp.yaml

feat: Align keycloakUrl parameter usage

---

deploy-templates/templates/oauth2-proxy/configmap.yaml

chore: Align oauth2-proxy issuer url

---

docs/supported-versions.md

docs: Update release timeline (#187)

---

deploy-templates/templates/oauth2-proxy/configmap.yaml

Reduce logging by enabling silence_ping_logging in oauth2-proxy component
Fixes #230 

feat: Implement `silence_ping_logging` Option in oauth2-proxy Configuration

---

deploy-templates/templates/keycloak/broker-idp.yaml
deploy-templates/templates/openshift/role_openshift.yaml
deploy-templates/templates/openshift/rolebinding_edp_kaniko_registry_editor.yaml
deploy-templates/templates/openshift/rolebinding_openshift.yaml
deploy-templates/templates/openshift/rolebinding_openshift_admin.yaml

chore: Update argocd diff

---

docs/operator-guide/install-velero.md

This pull request updates the Velero installation guide (install-velero.md) within the edp-install documentation to reflect the latest version and configurations for Velero. The update includes critical changes in version numbers, command line instructions, and configuration details to align with the latest best practices and operational requirements for installing Velero in a core cluster environment.
Key Changes:
Updated Velero version from v.2.14.13 to v.6.5.0.
Revised the values.yaml file to reflect the latest configurations, including:
Updated Velero and Velero AWS Plugin image versions.
Adjusted IAM role annotations to match the current AWS account and cluster naming conventions.
Removed outdated image tags and corrected instructions for setting security contexts and volume snapshot …

docs: Update velero installation guide(#235)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

Jira: EPMDEDP-13912
Fixes #239

chore: Update release version to 3.9.0

---

CHANGELOG.md
deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

Jira: EPMDEDP-13912
Fixes #239

chore: Update current development version

---

docs/operator-guide/install-edp.md
docs/operator-guide/jira-integration.md
docs/quick-start/platform-installation.md
docs/user-guide/git-server-overview.md

chore: Align EDP Install Documentation to 3.9.0

---

RELEASES.md

The change contains release notes for the 3.9.0 version.

docs: Update the RELEASES md file (#242)

---

RELEASES.md

Made the GitHub Container Registry support announcement more neutral in the RELEASES.md file.

docs: Adjust the RELEASES md file (#242)

---

RELEASES.md

This patchset contains more fixed for the RELEASES.md file.

docs: Adjust the RELEASES md file again (#242)

---

docs/operator-guide/install-edp.md
docs/operator-guide/upgrade-edp-3.9.md
docs/supported-versions.md
mkdocs.yml

docs: Upgrade Documentation for KubeRocketCI 3.9.0

---

deploy-templates/templates/external-secrets/externalsecret-ci-codemie.yaml

feat: Enable eso for ci-codemie

---

docs/overrides/main.html
mkdocs.yml

docs: Add annoounce for new documentation URL (#177)

---

deploy-templates/templates/marketplace/terminal.yaml

The onboarding of 'Terminal' via the marketplace section in the UI has been successfully enabled. 
Fixes #262 

feat: Enable Onboarding of 'Terminal' via Marketplace Section in UI (#262)

---

deploy-templates/templates/external-secrets/externalsecret-ci-codemie.yaml

chore: Align secret label

---

README.md

This minor change replaces EDP with KubeRocketCI in the note in the README.md file.

docs: Replace EDP with KubeRocketCI in README md (#278)

---

docs/overrides/main.html

Update link to docs
Fixes #278

docs: Update link to new docs (#278)

---

deploy-templates/README.md
deploy-templates/values.yaml

Added the ability to enable tekton-pipelines monitoring via values.yaml.
Fixes #268

feat: Add the ability to enable tekton-pipelines monitoring (#268)

---

CHANGELOG.md

This change updates the CHANGELOG.md file with the contents generated by the "make changelog" command.

docs: Update CHANGELOG md file

---

deploy-templates/templates/_helpers.tpl

Remove all OAuth2 proxy-related variables from the templates, and restore the secretStoreName variable for managing external secrets.
Fixes # (issue)
Helm templates were validated and deployed in the developers' environment.
Add any other context or screenshots about the feature request here.

fix: Align templates variables(#289)

---

deploy-templates/templates/marketplace/echo-server.yaml
deploy-templates/templates/marketplace/terminal.yaml

chore: Align marketplace repository path(#301)

---

deploy-templates/README.md
deploy-templates/values.yaml

Added support for BitBucket as GitProvider
Fixes #306

feat: Add Support for BitBucket as GitProvider (#306)

---

CHANGELOG.md

This change updates the CHANGELOG.md file

docs: Update changelog file for release notes (#292)

---

deploy-templates/README.md
deploy-templates/templates/external-secrets/externalsecret-gitprovider.yaml
deploy-templates/values.yaml

Move Git Providers data to separate AWS Parameter Stroe object
Fixes #309

chore: Move Git Providers data to separate AWS PS object (#309)

---

deploy-templates/templates/rbac/role_developer.yaml

chore: Enable permissions to configmaps for developers (#313)

---

deploy-templates/README.md
deploy-templates/templates/edp_config_map.yaml
deploy-templates/values.yaml

Add apiGatewayUrl field to edp-config Config Map
Fixes #316

chore: Add apiGatewayUrl field to edp-config CM (#316)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#318)

---

RELEASES.md

This change contains updates for RELEASES.md file.

docs: Update RELEASES md file (#311)

---

RELEASES.md

This minor change updates the RELEASES.md file to contain release notes for the 3.10.0 release.

docs: Update RELEASES md file in 3_10 branch (#311)

---

pull_request_template.md

Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #107

chore: Update Pull Request Template (#107)

---

deploy-templates/README.md
deploy-templates/values-no-ingress.yaml
deploy-templates/values.yaml

Update OIDC configuration for edp-headlamp Helm Chart.
Fixes #325

chore: Update OIDC configuration for edp-headlamp (#325)

---

deploy-templates/templates/crds/edp.epam.com_approvaltasks.yaml

chore: Add ApprovalTask CRD (#318)

---

deploy-templates/templates/rbac/role_developer.yaml

chore: Align permissions for developer to use approve feature (#332)

---

CHANGELOG.md
deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#335)

---

RELEASES.md

This change add 3.10.1 and 3.10.2 releases to RELEASES.md file.

docs: Add 3-10-1 and 3-10-2 releases to RELEASES md (#339)

---

deploy-templates/templates/edp_config_map.yaml

Align ArgoCD diff for edp-config Config Map
Fixes #344

chore: Align ArgoCD diff for edp-config Config Map (#344)

---

RELEASES.md

This minor change corrects inaccuracies in the RELEASES.md file.

docs: Replace EDP With KubeRocketCI in RELEASES md (#297)

---

mkdocs.yml

Update documentation redirect
Add any other context or screenshots about the feature request here.

docs: Update redirect to new documentation site (#352)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#356)

---

CHANGELOG.md
RELEASES.md

This change update the RELEASES.md file to contain the release notes for 3.10.3.

docs: Update releases md to 3-10-3

---

deploy-templates/README.md
deploy-templates/templates/edp_config_map.yaml
deploy-templates/values.yaml

chore: Enable availableClusters parameter in edp-config configmap (#365)

---

deploy-templates/README.md
deploy-templates/values.yaml

feat: Enable node selector for tekton pipelines

---

deploy-templates/templates/external-secrets/externalsecret-ci-codemie.yaml

chore: Disable CodeMie eso creation if path empty (#369)

---

deploy-templates/README.md
deploy-templates/values.yaml

feat: Enable node selector for tekton pipelines (#367)

---

deploy-templates/README.md
deploy-templates/templates/rbac/rolebinding_admin.yaml
deploy-templates/templates/rbac/rolebinding_developer.yaml
deploy-templates/templates/rbac/rolebinding_viewer.yaml
deploy-templates/values.yaml

feat: Enable flexible naming for default OIDC groups (#378)

---

deploy-templates/README.md
deploy-templates/values-custom-certs.yaml
deploy-templates/values-no-ingress.yaml
deploy-templates/values.yaml

Remove Tekton Dashboard from edp-tekton chart
Fixes #382

chore: Remove Tekton Dashboard from edp-tekton (#382)

---

deploy-templates/values.yaml

chore: Update values.yaml (#384)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#390)

---

deploy-templates/templates/rbac/role_developer.yaml

chore: Enable branches management for developers

---

deploy-templates/templates/edp_config_map.yaml

Align Argo CD diff for `edp-config` ConfigMap
Fixes #344

chore: Align Argo CD diff for edp-config ConfigMap (#344)

---

deploy-templates/templates/rbac/role_developer.yaml

Expand Developer Role Permissions for Deployment Flow and Environment resources.
Fixes #409

chore: Expand Developer Role Permissions (#409)

---

mkdocs.yml

This change add missing redirects in mkdocs to the new documentation site.
The documentation was successfully built on a local machine. Page redirect was tested successfully.

docs: Expand link redirects in docs (#408)

---

deploy-templates/README.md
deploy-templates/templates/edp_config_map.yaml
deploy-templates/values.yaml

chore: Add apiClusterEndpoint parameter for static kubeconfig generation

---

deploy-templates/templates/edp_config_map.yaml

fix: Fix typo in apiClusterEndpoint parameter

---

mkdocs.yml

Change-Id: Ib1b0eb61aaa796d772d5ac8eebbe6d28f15e5bb8
Please include a summary of the change and why it is needed.
Fixes #(issue)

chore: Add redirect links to the new docs (#414)

---

deploy-templates/README.md
deploy-templates/values.yaml

Expose `imagePullSecrets` field for the Tekton ServiceAccount.
Fixes #427

chore: Add imagePullSecrets field for Tekton ServiceAccount (#427)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#430)

---

deploy-templates/README.md
deploy-templates/values.yaml

Add ImagePullSecrets field for dependency Helm charts.
Fixes #438

chore: Add ImagePullSecrets field for dependency charts (#438)

---

deploy-templates/templates/krci_config_map.yaml

chore: Rename ConfigMap from 'edp-config' to 'krci-config'

---

RELEASES.md

This change describe release notes from the 3.11.0 release.
Markdown preview

docs: Describe release 3-11-0 in RELEASES md (#435)

---

CHANGELOG.md
deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#442)

---

RELEASES.md

This change contains release notes on 3.11.1 and documentation updates.
markdown preview

docs: Add 3-11-1 release notes and doc updates (#435)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#449)

---

mkdocs.yml

This change updates redirects from old site to new.
The "mkdocs serve" command works fine.

docs: Update link redirects in docs (#460)

---

deploy-templates/README.md
deploy-templates/templates/marketplace/antora.yaml
deploy-templates/templates/marketplace/csharp-dotnet-6.0.yaml
deploy-templates/templates/marketplace/echo-server.yaml
deploy-templates/templates/marketplace/fastapi.yaml
deploy-templates/templates/marketplace/gin.yaml
deploy-templates/templates/marketplace/springboot-java17.yaml
deploy-templates/templates/marketplace/terminal.yaml
deploy-templates/templates/marketplace/terraform-module.yaml
deploy-templates/values.yaml

feat: Add flag to disable default marketplace templates

---

RELEASES.md

This change contains release notes for the 3.11.3 release version.
markdown preview

docs: Update RELEASES md to contain 3-11-3 notes (#476)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md
deploy-templates/values.yaml

chore: Update current development version (#482)

---

CHANGELOG.md
RELEASES.md

This change contains release notes for the 3.12.0 release.
Fixes #(issue)
Markdown preview.

docs: Update the RELEASES md file for 3 12 (#480)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md
deploy-templates/values.yaml

chore: Remove gitfusion as a part of edp-install (#482)

---

deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

Please include a summary of the change and why it is needed.
Fixes #499 
Add any other context or screenshots about the feature request here.

chore: Update current development version (#499)

---

RELEASES.md

This change updates the RELEASES.md file to contain release notes for the 3.12.1-3.12.2 versions.
Markdown preview

docs: Add 3-12-1 and 3-12-2 to RELEASES md (#504)

---

CHANGELOG.md
deploy-templates/Chart.lock
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#506)
